# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'acetrainer' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for acetrainer
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'TesseractOCRiOS', '4.0.0'
  pod "PromiseKit", "~> 4.0"
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
  end

  target 'acetrainerTests' do
    inherit! :search_paths
    # Pods for testing
  end


end
